<a href="https://colab.research.google.com/github/CAVASOL/aiffel_quest/blob/main/ML_node/ML_with_Python_ScikitLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    'menu': ['[인기]아이펠치킨','닭강정','간장치킨','마늘치킨','파닭','승일양념치킨','양념반후라이드반','황금후라이드','[베스트]풀잎치킨'],
    'price': [16000,15000,14000,14000,14000,13000,13000,12000,9900],
    'size' : [11,12,9,9,11,10,10,10,10],
    'cal' : [1200.0,1500.0,1600.0,1800.0,1300.0,1400.0,1300.0,1000.0,1000.0],
    'promo' : [0.5,0.2,0.2,0.2,0.2,0.2,0.2,0.2,np.nan],
    'promo_price' : [8000.0,12000.0,11200.0,11200.0,11200.0,10400.0,10400.0,9600.0,np.nan],
    'origin' : ['Kor','Somewhere','Kor','Kor','Somewhere','Kor','Kor','Kor','Kor'],
    'get_fat' : ['nah','ye','ye','ye','ye','ye','ye','nah','nah'],
    'takeit' : ['defo','ignor','ignor','ignor','ignor','ignor','ignor','defo','defo']
})
data.to_csv('final_modudak.csv', index=False)
data


menu  price  size     cal  promo  promo_price     origin get_fat  \
0  [인기]아이펠치킨  16000    11  1200.0    0.5       8000.0        Kor     nah   
1        닭강정  15000    12  1500.0    0.2      12000.0  Somewhere      ye   
2       간장치킨  14000     9  1600.0    0.2      11200.0        Kor      ye   
3       마늘치킨  14000     9  1800.0    0.2      11200.0        Kor      ye   
4         파닭  14000    11  1300.0    0.2      11200.0  Somewhere      ye   
5     승일양념치킨  13000    10  1400.0    0.2      10400.0        Kor      ye   
6   양념반후라이드반  13000    10  1300.0    0.2      10400.0        Kor      ye   
7     황금후라이드  12000    10  1000.0    0.2       9600.0        Kor     nah   
8  [베스트]풀잎치킨   9900    10  1000.0    NaN          NaN        Kor     nah   

  takeit  
0   defo  
1  ignor  
2  ignor  
3  ignor  
4  ignor  
5  ignor  
6  ignor  
7   defo  
8   defo

In [ ]:
#데이터 변경
data.loc[2, 'origin'] = 'USA'

In [ ]:
#활용할 데이터 선택
df = data[['price', 'size', 'cal', 'origin', 'get_fat']].copy()
df

price  size     cal     origin get_fat
0  16000    11  1200.0        Kor     nah
1  15000    12  1500.0  Somewhere      ye
2  14000     9  1600.0        USA      ye
3  14000     9  1800.0        Kor      ye
4  14000    11  1300.0  Somewhere      ye
5  13000    10  1400.0        Kor      ye
6  13000    10  1300.0        Kor      ye
7  12000    10  1000.0        Kor     nah
8   9900    10  1000.0        Kor     nah

In [ ]:
#df type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   price    9 non-null      int64  
 1   size     9 non-null      int64  
 2   cal      9 non-null      float64
 3   origin   9 non-null      object 
 4   get_fat  9 non-null      object 
dtypes: float64(1), int64(2), object(2)
memory usage: 488.0+ bytes


In [ ]:
#레이블 인코딩
#Kor=0, Somewhere=1, USA=2
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['origin'])
le.transform(df['origin'])

array([0, 1, 2, 0, 1, 0, 0, 0, 0])

In [ ]:
#fit_transform
le.fit_transform(df['origin'])

array([0, 1, 2, 0, 1, 0, 0, 0, 0])

In [ ]:
df['origin'] = le.fit_transform(df['origin'])
df

price  size     cal  origin get_fat
0  16000    11  1200.0       0     nah
1  15000    12  1500.0       1      ye
2  14000     9  1600.0       2      ye
3  14000     9  1800.0       0      ye
4  14000    11  1300.0       1      ye
5  13000    10  1400.0       0      ye
6  13000    10  1300.0       0      ye
7  12000    10  1000.0       0     nah
8   9900    10  1000.0       0     nah

In [ ]:
#label encoding for get_fat
#nah=0, ye=1
df['get_fat'] = le.fit_transform(df['get_fat'])
df

price  size     cal  origin  get_fat
0  16000    11  1200.0       0        0
1  15000    12  1500.0       1        1
2  14000     9  1600.0       2        1
3  14000     9  1800.0       0        1
4  14000    11  1300.0       1        1
5  13000    10  1400.0       0        1
6  13000    10  1300.0       0        1
7  12000    10  1000.0       0        0
8   9900    10  1000.0       0        0

In [ ]:
#활용할 데이터 선택
df = data[['price', 'size', 'cal', 'origin', 'get_fat']].copy()
df

price  size     cal     origin get_fat
0  16000    11  1200.0        Kor     nah
1  15000    12  1500.0  Somewhere      ye
2  14000     9  1600.0        USA      ye
3  14000     9  1800.0        Kor      ye
4  14000    11  1300.0  Somewhere      ye
5  13000    10  1400.0        Kor      ye
6  13000    10  1300.0        Kor      ye
7  12000    10  1000.0        Kor     nah
8   9900    10  1000.0        Kor     nah

In [ ]:
#object 타입 선택
# cols = ['origin', 'get_fat']
cols = df.select_dtypes(include='object').columns

In [ ]:
#레이블 인코딩 한 번에
from sklearn.preprocessing import LabelEncoder

for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [ ]:
df

price  size     cal  origin  get_fat
0  16000    11  1200.0       0        0
1  15000    12  1500.0       1        1
2  14000     9  1600.0       2        1
3  14000     9  1800.0       0        1
4  14000    11  1300.0       1        1
5  13000    10  1400.0       0        1
6  13000    10  1300.0       0        1
7  12000    10  1000.0       0        0
8   9900    10  1000.0       0        0

In [ ]:
df = data[['price', 'size', 'cal', 'origin', 'get_fat']].copy()
df

price  size     cal     origin get_fat
0  16000    11  1200.0        Kor     nah
1  15000    12  1500.0  Somewhere      ye
2  14000     9  1600.0        USA      ye
3  14000     9  1800.0        Kor      ye
4  14000    11  1300.0  Somewhere      ye
5  13000    10  1400.0        Kor      ye
6  13000    10  1300.0        Kor      ye
7  12000    10  1000.0        Kor     nah
8   9900    10  1000.0        Kor     nah

In [ ]:
#OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
cat = ohe.fit_transform(df[['origin']])
cat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
#categories
ohe.categories_

[array(['Kor', 'Somewhere', 'USA'], dtype=object)]

In [ ]:
#feature, name and category
ohe.get_feature_names_out()

array(['origin_Kor', 'origin_Somewhere', 'origin_USA'], dtype=object)

In [ ]:
#transform to dataframe
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

origin_Kor  origin_Somewhere  origin_USA
0         1.0               0.0         0.0
1         0.0               1.0         0.0
2         0.0               0.0         1.0
3         1.0               0.0         0.0
4         0.0               1.0         0.0
5         1.0               0.0         0.0
6         1.0               0.0         0.0
7         1.0               0.0         0.0
8         1.0               0.0         0.0

In [ ]:
#merge dataframe
df = pd.concat([df, df_cat], axis=1)
df

price  size     cal     origin get_fat  origin_Kor  origin_Somewhere  \
0  16000    11  1200.0        Kor     nah         1.0               0.0   
1  15000    12  1500.0  Somewhere      ye         0.0               1.0   
2  14000     9  1600.0        USA      ye         0.0               0.0   
3  14000     9  1800.0        Kor      ye         1.0               0.0   
4  14000    11  1300.0  Somewhere      ye         0.0               1.0   
5  13000    10  1400.0        Kor      ye         1.0               0.0   
6  13000    10  1300.0        Kor      ye         1.0               0.0   
7  12000    10  1000.0        Kor     nah         1.0               0.0   
8   9900    10  1000.0        Kor     nah         1.0               0.0   

   origin_USA  
0         0.0  
1         0.0  
2         1.0  
3         0.0  
4         0.0  
5         0.0  
6         0.0  
7         0.0  
8         0.0

In [ ]:
#기존 컬럼 삭제, origin 삭제하기
df = df.drop(['origin'], axis=1)
df

price  size     cal get_fat  origin_Kor  origin_Somewhere  origin_USA
0  16000    11  1200.0     nah         1.0               0.0         0.0
1  15000    12  1500.0      ye         0.0               1.0         0.0
2  14000     9  1600.0      ye         0.0               0.0         1.0
3  14000     9  1800.0      ye         1.0               0.0         0.0
4  14000    11  1300.0      ye         0.0               1.0         0.0
5  13000    10  1400.0      ye         1.0               0.0         0.0
6  13000    10  1300.0      ye         1.0               0.0         0.0
7  12000    10  1000.0     nah         1.0               0.0         0.0
8   9900    10  1000.0     nah         1.0               0.0         0.0

In [ ]:
#활용할 데이터 선택
df = data[['price', 'size', 'cal', 'origin', 'get_fat']].copy()
df

price  size     cal     origin get_fat
0  16000    11  1200.0        Kor     nah
1  15000    12  1500.0  Somewhere      ye
2  14000     9  1600.0        USA      ye
3  14000     9  1800.0        Kor      ye
4  14000    11  1300.0  Somewhere      ye
5  13000    10  1400.0        Kor      ye
6  13000    10  1300.0        Kor      ye
7  12000    10  1000.0        Kor     nah
8   9900    10  1000.0        Kor     nah

In [ ]:
cols = df.select_dtypes(include='object').columns
ohe = OneHotEncoder(sparse=False)
cat = ohe.fit_transform(df[cols])
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

origin_Kor  origin_Somewhere  origin_USA  get_fat_nah  get_fat_ye
0         1.0               0.0         0.0          1.0         0.0
1         0.0               1.0         0.0          0.0         1.0
2         0.0               0.0         1.0          0.0         1.0
3         1.0               0.0         0.0          0.0         1.0
4         0.0               1.0         0.0          0.0         1.0
5         1.0               0.0         0.0          0.0         1.0
6         1.0               0.0         0.0          0.0         1.0
7         1.0               0.0         0.0          1.0         0.0
8         1.0               0.0         0.0          1.0         0.0

In [ ]:
df = pd.concat([df, df_cat], axis=1)
df.head()

price  size     cal     origin get_fat  origin_Kor  origin_Somewhere  \
0  16000    11  1200.0        Kor     nah         1.0               0.0   
1  15000    12  1500.0  Somewhere      ye         0.0               1.0   
2  14000     9  1600.0        USA      ye         0.0               0.0   
3  14000     9  1800.0        Kor      ye         1.0               0.0   
4  14000    11  1300.0  Somewhere      ye         0.0               1.0   

   origin_USA  get_fat_nah  get_fat_ye  
0         0.0          1.0         0.0  
1         0.0          0.0         1.0  
2         1.0          0.0         1.0  
3         0.0          0.0         1.0  
4         0.0          0.0         1.0

In [ ]:
df = df.drop(cols, axis=1)
df

price  size     cal  origin_Kor  origin_Somewhere  origin_USA  get_fat_nah  \
0  16000    11  1200.0         1.0               0.0         0.0          1.0   
1  15000    12  1500.0         0.0               1.0         0.0          0.0   
2  14000     9  1600.0         0.0               0.0         1.0          0.0   
3  14000     9  1800.0         1.0               0.0         0.0          0.0   
4  14000    11  1300.0         0.0               1.0         0.0          0.0   
5  13000    10  1400.0         1.0               0.0         0.0          0.0   
6  13000    10  1300.0         1.0               0.0         0.0          0.0   
7  12000    10  1000.0         1.0               0.0         0.0          1.0   
8   9900    10  1000.0         1.0               0.0         0.0          1.0   

   get_fat_ye  
0         0.0  
1         1.0  
2         1.0  
3         1.0  
4         1.0  
5         1.0  
6         1.0  
7         0.0  
8         0.0

In [ ]:
#활용할 데이터 선택
df = data[['price', 'size', 'cal', 'origin', 'get_fat']].copy()
df.head()

price  size     cal     origin get_fat
0  16000    11  1200.0        Kor     nah
1  15000    12  1500.0  Somewhere      ye
2  14000     9  1600.0        USA      ye
3  14000     9  1800.0        Kor      ye
4  14000    11  1300.0  Somewhere      ye

In [ ]:
#판다스를 활용한 원핫인코딩
df = pd.get_dummies(df)
df

price  size     cal  origin_Kor  origin_Somewhere  origin_USA  get_fat_nah  \
0  16000    11  1200.0           1                 0           0            1   
1  15000    12  1500.0           0                 1           0            0   
2  14000     9  1600.0           0                 0           1            0   
3  14000     9  1800.0           1                 0           0            0   
4  14000    11  1300.0           0                 1           0            0   
5  13000    10  1400.0           1                 0           0            0   
6  13000    10  1300.0           1                 0           0            0   
7  12000    10  1000.0           1                 0           0            1   
8   9900    10  1000.0           1                 0           0            1   

   get_fat_ye  
0           0  
1           1  
2           1  
3           1  
4           1  
5           1  
6           1  
7           0  
8           0

In [ ]:
df.head()

price  size     cal  origin_Kor  origin_Somewhere  origin_USA  get_fat_nah  \
0  16000    11  1200.0           1                 0           0            1   
1  15000    12  1500.0           0                 1           0            0   
2  14000     9  1600.0           0                 0           1            0   
3  14000     9  1800.0           1                 0           0            0   
4  14000    11  1300.0           0                 1           0            0   

   get_fat_ye  
0           0  
1           1  
2           1  
3           1  
4           1

In [ ]:
#StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(df[['price']])

array([[ 1.54246993],
       [ 0.94150762],
       [ 0.34054531],
       [ 0.34054531],
       [ 0.34054531],
       [-0.260417  ],
       [-0.260417  ],
       [-0.86137931],
       [-2.12340016]])

In [ ]:
#StandardScaler 여러 변수에 적용해보기
cols = ['price', 'size', 'cal']
scaler = StandardScaler()
df[cols] = scaler.fit_transform(df[cols])
df

price      size       cal  origin_Kor  origin_Somewhere  origin_USA  \
0  1.542470  0.848875 -0.577920           1                 0           0   
1  0.941508  1.940285  0.622376           0                 1           0   
2  0.340545 -1.333946  1.022475           0                 0           1   
3  0.340545 -1.333946  1.822672           1                 0           0   
4  0.340545  0.848875 -0.177822           0                 1           0   
5 -0.260417 -0.242536  0.222277           1                 0           0   
6 -0.260417 -0.242536 -0.177822           1                 0           0   
7 -0.861379 -0.242536 -1.378118           1                 0           0   
8 -2.123400 -0.242536 -1.378118           1                 0           0   

   get_fat_nah  get_fat_ye  
0            1           0  
1            0           1  
2            0           1  
3            0           1  
4            0           1  
5            0           1  
6            0           1  
7            1           0  
8            1           0

In [ ]:
#MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
cols = ['price', 'size', 'cal']
scaler = MinMaxScaler()
df[cols] = scaler.fit_transform(df[cols])
df

price      size    cal  origin_Kor  origin_Somewhere  origin_USA  \
0  1.000000  0.666667  0.250           1                 0           0   
1  0.836066  1.000000  0.625           0                 1           0   
2  0.672131  0.000000  0.750           0                 0           1   
3  0.672131  0.000000  1.000           1                 0           0   
4  0.672131  0.666667  0.375           0                 1           0   
5  0.508197  0.333333  0.500           1                 0           0   
6  0.508197  0.333333  0.375           1                 0           0   
7  0.344262  0.333333  0.000           1                 0           0   
8  0.000000  0.333333  0.000           1                 0           0   

   get_fat_nah  get_fat_ye  
0            1           0  
1            0           1  
2            0           1  
3            0           1  
4            0           1  
5            0           1  
6            0           1  
7            1           0  
8            1           0

In [ ]:
#open sklearn data
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()
dataset

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [ ]:
#feature name
dataset.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
#target
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
#check data
dataset.data[:2]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02]])

In [ ]:
#create dataframe, array -> dataframe
cancer_df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
cancer_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [ ]:
#add target
cancer_df['target'] = dataset.target
cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [ ]:
#check dataset, load_*
import sklearn.datasets

sklearn.datasets.__all__


['clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_species_distributions',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_rcv1',
 'fetch_kddcup99',
 'fetch_openml',
 'get_data_home',
 'load_boston',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_breast_cancer',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_circles',
 'make_classification',
 'make_checkerboard',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2',
 'make_low_rank_matrix',
 'make_moons',
 'make_multilabel_classification',
 'make_regression',
 'make_s_curve',
 'make_sparse_coded_signal',
 'make_sparse_spd_matrix',
 'make_sparse_uncorrelated',
 'make_spd_matrix',
 'make_swiss_roll']

In [ ]:
#open diabetes data
from sklearn.datasets import load_diabetes
dataset = load_diabetes()

In [ ]:
#create dataframe
diabetes_df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
diabetes_df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

In [ ]:
#add target
diabetes_df['target'] = dataset.target

In [ ]:
diabetes_df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [ ]:
#검증데이터 분리 - open lib
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    cancer_df.drop('target', axis=1),
    cancer_df['target'],
    test_size=0.3,
    random_state=1004)

In [ ]:
#train 데이터 확인(X)
X_train.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
350       11.660         17.07           73.70      421.0          0.07561   
384       13.280         13.72           85.79      541.8          0.08363   
7         13.710         20.83           90.20      577.9          0.11890   
557        9.423         27.88           59.26      271.3          0.08123   
49        13.490         22.30           86.91      561.0          0.08752   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
350           0.03630        0.008306              0.01162         0.1671   
384           0.08575        0.050770              0.02864         0.1617   
7             0.16450        0.093660              0.05985         0.2196   
557           0.04971        0.000000              0.00000         0.1742   
49            0.07698        0.047510              0.03384         0.1809   

     mean fractal dimension  ...  worst radius  worst texture  \
350                 0.05731  ...         13.28          19.74   
384                 0.05594  ...         14.24          17.37   
7                   0.07451  ...         17.06          28.14   
557                 0.06059  ...         10.49          34.24   
49                  0.05718  ...         15.15          31.82   

     worst perimeter  worst area  worst smoothness  worst compactness  \
350            83.61       542.5           0.09958            0.06476   
384            96.59       623.7           0.11660            0.26850   
7             110.60       897.0           0.16540            0.36820   
557            66.50       330.6           0.10730            0.07158   
49             99.00       698.8           0.11620            0.17110   

     worst concavity  worst concave points  worst symmetry  \
350          0.03046               0.04262          0.2731   
384          0.28660               0.09173          0.2736   
7            0.26780               0.15560          0.3196   
557          0.00000               0.00000          0.2475   
49           0.22820               0.12820          0.2871   

     worst fractal dimension  
350                  0.06825  
384                  0.07320  
7                    0.11510  
557                  0.06969  
49                   0.06917  

[5 rows x 30 columns]

In [ ]:
#학습데이터 확인(y)
y_train.head()

350    1
384    1
7      0
557    1
49     1
Name: target, dtype: int64

In [ ]:
#data size
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((398, 30), (171, 30), (398,), (171,))

In [ ]:
#의사결정나무(Decision Tree)
from sklearn.tree import DecisionTreeClassifier

#모델 선택
model = DecisionTreeClassifier()

#학습
model.fit(X_train, y_train)

#예측
pred = model.predict(X_test)
pred

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
#평가 accuracy_score(실제값, 예측값)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9005847953216374

In [ ]:
# ML - Regression 회귀
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    diabetes_df.drop('target', axis=1),
    diabetes_df['target'],
    test_size=0.3,
    random_state=1004)

In [ ]:
X_train.head()

age       sex       bmi        bp        s1        s2        s3  \
232  0.012648  0.050680  0.000261 -0.011409  0.039710  0.057245 -0.039719   
81   0.012648  0.050680 -0.022373 -0.029771  0.010815  0.028435 -0.021311   
227  0.067136  0.050680 -0.029918  0.057449 -0.000193 -0.015719  0.074412   
334 -0.060003  0.050680 -0.047163 -0.022885 -0.071743 -0.057681 -0.006584   
83  -0.038207 -0.044642  0.009961 -0.046985 -0.059359 -0.052983 -0.010266   

           s4        s5        s6  
232  0.056081  0.024053  0.032059  
81   0.034309 -0.006080 -0.001078  
227 -0.050564 -0.038459  0.007207  
334 -0.039493 -0.062913 -0.054925  
83  -0.039493 -0.015998 -0.042499

In [ ]:
y_train.head()

232    259.0
81      51.0
227    108.0
334     72.0
83     210.0
Name: target, dtype: float64

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((309, 10), (133, 10), (309,), (133,))

In [ ]:
#LinearRegression 선형회귀

from sklearn.linear_model import LinearRegression

#모델 선택
model = LinearRegression()

#학습
model.fit(X_train, y_train)

#예측
pred = model.predict(X_test)
pred

array([128.42584096, 135.0870178 , 154.78166657, 106.09435851,
       149.54313889, 165.32784413, 140.28955883, 167.95778147,
        69.4503107 , 189.42664051, 144.9847161 , 150.11273979,
       211.16078839, 108.59060526, 160.38284395, 154.09983174,
       198.78261008, 101.15867269, 165.82927955, 196.03539157,
       147.16334011, 108.25672705, 207.28165472, 127.53118326,
       181.85939663, 228.49956035,  86.59826865, 155.35000645,
       182.49645024, 182.96618563, 207.62865615, 199.81160132,
       157.36018064,  61.82420828,  88.11382212,  95.75044874,
       134.03529608,  85.95868919, 177.696808  , 249.40294124,
       171.77254108, 204.7152808 , 239.12264861,  89.25163253,
       244.20493803, 180.3631026 , 161.10419087, 119.1476007 ,
       102.82444201, 153.35453384, 129.06516018, 208.80060788,
       107.93804188, 138.812454  , 166.04360408,  86.04372546,
       181.03333757, 117.98035042,  79.04611318, 127.20684737,
       194.06146795, 205.13560483, 233.85068191,  48.53

In [ ]:
#mean_squared_error(실제값, 예측값) MSE - 낮을 수록 성능이 좋다!

from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)

3229.4396061827333